
# ------------------------
# Protocol Configuration
# ------------------------
# protocol: 使用的协议 (http 或 https)
protocol = https

# host: 目标服务器（不包含协议前缀）
host = 10.201.0.123 

users = 135
spawn-rate = 20

# ------- Web UI Settings -------
headless = false
autostart = true


web-host = 0.0.0.0      # 僅本機測試可留空，想遠端瀏覽就綁 0.0.0.0
web-port = 8089
run-time = 10m
stop-timeout = 10s

locustfile = ./locustfile.py


# Use an external JSON file to avoid inline parsing/escaping issues
config-users = ./profiles/config-users.json


# 統計輸出
csv = ./results/run
csv-full-history = true
html = ./results/report.html
logfile = ./results/locust.log
loglevel = INFO


